openapi: 3.2.0
info:
  title: Member Service Domains API
  version: 2.10.1
tags:
- name: Domains
paths:
  /domains/:
    get:
      tags:
      - Domains
      summary: Get Domains
      operationId: get_domains_domains__get
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          minimum: 1
          default: 1
          title: Page
      - name: size
        in: query
        required: false
        schema:
          type: integer
          maximum: 100
          minimum: 1
          default: 50
          title: Size
      - name: display_name
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Display Name
      - name: order_by
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          default: created_at
          title: Order By
      - name: domain_name
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Domain Name
      - name: user__id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: User  Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_Domain_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - OAuth2AuthorizationCodeBearer: []
    post:
      tags:
      - Domains
      summary: Create Domain
      operationId: create_domain_domains__post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDomainInput'
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                format: uuid
                title: Response Create Domain Domains  Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - OAuth2AuthorizationCodeBearer: []
  /domains/{domain_id}:
    get:
      tags:
      - Domains
      summary: Get Domain By Id
      operationId: get_domain_by_id_domains__domain_id__get
      parameters:
      - name: domain_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
          title: Domain Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainWithDefaultRoles'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - OAuth2AuthorizationCodeBearer: []
    put:
      tags:
      - Domains
      summary: Update Domain
      operationId: update_domain_domains__domain_id__put
      parameters:
      - name: domain_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
          title: Domain Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDomainInput'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                format: uuid
                title: Response Update Domain Domains  Domain Id  Put
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - OAuth2AuthorizationCodeBearer: []
  /domains/{domain_name}/organisations/:
    post:
      tags:
      - Domains
      summary: Add Domain Organisation
      operationId: add_domain_organisation_domains__domain_name__organisations__post
      parameters:
      - name: domain_name
        in: path
        required: true
        schema:
          type: string
          title: Domain Name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddDomainOrganisationInput'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                title: Response Add Domain Organisation Domains  Domain Name  Organisations  Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - OAuth2AuthorizationCodeBearer: []
    delete:
      tags:
      - Domains
      summary: Remove Domain Organisation
      operationId: remove_domain_organisation_domains__domain_name__organisations__delete
      parameters:
      - name: domain_name
        in: path
        required: true
        schema:
          type: string
          title: Domain Name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveDomainOrganisationInput'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                title: Response Remove Domain Organisation Domains  Domain Name  Organisations  Delete
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - OAuth2AuthorizationCodeBearer: []
  /domain-input-checks/:
    post:
      tags:
      - Domains
      summary: Check Domain Name
      operationId: check_domain_name_domain_input_checks__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganisationName'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - OAuth2AuthorizationCodeBearer: []
components:
  schemas:
    RoleWithoutPermissions:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        created_at:
          type: string
          format: date-time
          title: Created At
        updated_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Updated At
        name:
          type: string
          title: Name
        display_name:
          anyOf:
          - type: string
          - type: 'null'
          title: Display Name
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        organisation:
          anyOf:
          - $ref: '#/components/schemas/Organisation'
          - type: 'null'
      type: object
      required:
      - name
      title: RoleWithoutPermissions
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    UpdateDomainInput:
      properties:
        display_name:
          anyOf:
          - type: string
          - type: 'null'
          title: Display Name
        default_role_names:
          anyOf:
          - items:
              type: string
            type: array
          - type: 'null'
          title: Default Role Names
        system_type:
          anyOf:
          - $ref: '#/components/schemas/SystemTypes'
          - type: 'null'
      type: object
      title: UpdateDomainInput
    DomainWithDefaultRoles:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        created_at:
          type: string
          format: date-time
          title: Created At
        updated_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Updated At
        name:
          type: string
          title: Name
        display_name:
          type: string
          title: Display Name
        is_domain:
          type: boolean
          title: Is Domain
        system_type:
          anyOf:
          - $ref: '#/components/schemas/SystemTypes'
          - type: 'null'
        default_roles:
          anyOf:
          - items:
              $ref: '#/components/schemas/RoleWithoutPermissions'
            type: array
          - type: 'null'
          title: Default Roles
          default: []
        organisations:
          items:
            $ref: '#/components/schemas/Organisation'
          type: array
          title: Organisations
        reference_domain:
          anyOf:
          - type: string
          - type: 'null'
          title: Reference Domain
      type: object
      required:
      - name
      - display_name
      - is_domain
      - organisations
      title: DomainWithDefaultRoles
    SystemTypes:
      type: string
      enum:
      - ensure
      - build
      - dpp
      - see
      title: SystemTypes
    Organisation:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        created_at:
          type: string
          format: date-time
          title: Created At
        updated_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Updated At
        name:
          type: string
          title: Name
        display_name:
          type: string
          title: Display Name
        is_domain:
          type: boolean
          title: Is Domain
        system_type:
          anyOf:
          - $ref: '#/components/schemas/SystemTypes'
          - type: 'null'
      type: object
      required:
      - name
      - display_name
      - is_domain
      title: Organisation
      description: 'A model representing an organisation.


        The field `name` is unique.'
    OrganisationName:
      properties:
        name:
          type: string
          maxLength: 40
          minLength: 3
          pattern: ^[a-z0-9]+[a-z0-9-]+$
          title: Name
      type: object
      required:
      - name
      title: OrganisationName
    Page_Domain_:
      properties:
        items:
          items:
            $ref: '#/components/schemas/Domain'
          type: array
          title: Items
        total:
          type: integer
          minimum: 0.0
          title: Total
        page:
          type: integer
          minimum: 1.0
          title: Page
        size:
          type: integer
          minimum: 1.0
          title: Size
        pages:
          type: integer
          minimum: 0.0
          title: Pages
      type: object
      required:
      - items
      - total
      - page
      - size
      - pages
      title: Page[Domain]
    AddDomainOrganisationInput:
      properties:
        organisation_name:
          type: string
          title: Organisation Name
      type: object
      required:
      - organisation_name
      title: AddDomainOrganisationInput
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    RemoveDomainOrganisationInput:
      properties:
        organisation_name:
          type: string
          title: Organisation Name
      type: object
      required:
      - organisation_name
      title: RemoveDomainOrganisationInput
    CreateDomainInput:
      properties:
        display_name:
          anyOf:
          - type: string
          - type: 'null'
          title: Display Name
        default_role_names:
          anyOf:
          - items:
              type: string
            type: array
          - type: 'null'
          title: Default Role Names
        system_type:
          anyOf:
          - $ref: '#/components/schemas/SystemTypes'
          - type: 'null'
        name:
          type: string
          maxLength: 40
          minLength: 3
          pattern: ^[a-z0-9]+[a-z0-9-]+$
          title: Name
        reference_domain:
          anyOf:
          - type: string
          - type: 'null'
          title: Reference Domain
      type: object
      required:
      - name
      title: CreateDomainInput
    Domain:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        created_at:
          type: string
          format: date-time
          title: Created At
        updated_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Updated At
        name:
          type: string
          title: Name
        display_name:
          type: string
          title: Display Name
        is_domain:
          type: boolean
          title: Is Domain
        system_type:
          anyOf:
          - $ref: '#/components/schemas/SystemTypes'
          - type: 'null'
        organisations:
          items:
            $ref: '#/components/schemas/Organisation'
          type: array
          title: Organisations
        reference_domain:
          anyOf:
          - type: string
          - type: 'null'
          title: Reference Domain
      type: object
      required:
      - name
      - display_name
      - is_domain
      - organisations
      title: Domain
  securitySchemes:
    OAuth2AuthorizationCodeBearer:
      type: oauth2
      flows:
        authorizationCode:
          scopes: {}
          authorizationUrl: https://blocks.simbachain.com/api/member-service-validator/oauth/authorize
          tokenUrl: https://blocks.simbachain.com/api/member-service-validator/oauth/token
