openapi: 3.2.0
info:
  title: Member Service Organisations API
  version: 2.10.1
tags:
- name: Organisations
paths:
  /organisations/:
    get:
      tags:
      - Organisations
      summary: Get Organisations
      operationId: get_organisations_organisations__get
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          minimum: 1
          default: 1
          title: Page
      - name: size
        in: query
        required: false
        schema:
          type: integer
          maximum: 100
          minimum: 1
          default: 50
          title: Size
      - name: display_name
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Display Name
      - name: order_by
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          default: created_at
          title: Order By
      - name: organisation_name
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Organisation Name
      - name: user__id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: User  Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_Organisation_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - OAuth2AuthorizationCodeBearer: []
    post:
      tags:
      - Organisations
      summary: Create Organisation
      operationId: create_organisation_organisations__post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrganisationInput'
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                format: uuid
                title: Response Create Organisation Organisations  Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - OAuth2AuthorizationCodeBearer: []
  /organisations/{organisation_id}:
    get:
      tags:
      - Organisations
      summary: Get Organisation By Id
      operationId: get_organisation_by_id_organisations__organisation_id__get
      parameters:
      - name: organisation_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
          title: Organisation Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganisationWithDefaultRoles'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - OAuth2AuthorizationCodeBearer: []
    put:
      tags:
      - Organisations
      summary: Update Organisation
      operationId: update_organisation_organisations__organisation_id__put
      parameters:
      - name: organisation_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
          title: Organisation Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOrganisationInput'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                format: uuid
                title: Response Update Organisation Organisations  Organisation Id  Put
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - OAuth2AuthorizationCodeBearer: []
  /organisations/{organisation_name}/users/{user_id}:
    delete:
      tags:
      - Organisations
      summary: Remove User From Organisation
      operationId: remove_user_from_organisation_organisations__organisation_name__users__user_id__delete
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
          title: User Id
      - name: organisation_name
        in: path
        required: true
        schema:
          type: string
          title: Organisation Name
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - OAuth2AuthorizationCodeBearer: []
  /organisation-input-checks/:
    post:
      tags:
      - Organisations
      summary: Check Organisation Name
      operationId: check_organisation_name_organisation_input_checks__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganisationName'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - OAuth2AuthorizationCodeBearer: []
components:
  schemas:
    RoleWithoutPermissions:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        created_at:
          type: string
          format: date-time
          title: Created At
        updated_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Updated At
        name:
          type: string
          title: Name
        display_name:
          anyOf:
          - type: string
          - type: 'null'
          title: Display Name
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        organisation:
          anyOf:
          - $ref: '#/components/schemas/Organisation'
          - type: 'null'
      type: object
      required:
      - name
      title: RoleWithoutPermissions
    OrganisationWithDefaultRoles:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        created_at:
          type: string
          format: date-time
          title: Created At
        updated_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Updated At
        name:
          type: string
          title: Name
        display_name:
          type: string
          title: Display Name
        is_domain:
          type: boolean
          title: Is Domain
        system_type:
          anyOf:
          - $ref: '#/components/schemas/SystemTypes'
          - type: 'null'
        default_roles:
          anyOf:
          - items:
              $ref: '#/components/schemas/RoleWithoutPermissions'
            type: array
          - type: 'null'
          title: Default Roles
          default: []
      type: object
      required:
      - name
      - display_name
      - is_domain
      title: OrganisationWithDefaultRoles
    Page_Organisation_:
      properties:
        items:
          items:
            $ref: '#/components/schemas/Organisation'
          type: array
          title: Items
        total:
          type: integer
          minimum: 0.0
          title: Total
        page:
          type: integer
          minimum: 1.0
          title: Page
        size:
          type: integer
          minimum: 1.0
          title: Size
        pages:
          type: integer
          minimum: 0.0
          title: Pages
      type: object
      required:
      - items
      - total
      - page
      - size
      - pages
      title: Page[Organisation]
    UpdateOrganisationInput:
      properties:
        display_name:
          anyOf:
          - type: string
          - type: 'null'
          title: Display Name
        default_role_names:
          anyOf:
          - items:
              type: string
            type: array
          - type: 'null'
          title: Default Role Names
        system_type:
          anyOf:
          - $ref: '#/components/schemas/SystemTypes'
          - type: 'null'
      type: object
      title: UpdateOrganisationInput
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    SystemTypes:
      type: string
      enum:
      - ensure
      - build
      - dpp
      - see
      title: SystemTypes
    Organisation:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        created_at:
          type: string
          format: date-time
          title: Created At
        updated_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Updated At
        name:
          type: string
          title: Name
        display_name:
          type: string
          title: Display Name
        is_domain:
          type: boolean
          title: Is Domain
        system_type:
          anyOf:
          - $ref: '#/components/schemas/SystemTypes'
          - type: 'null'
      type: object
      required:
      - name
      - display_name
      - is_domain
      title: Organisation
      description: 'A model representing an organisation.


        The field `name` is unique.'
    CreateOrganisationInput:
      properties:
        display_name:
          anyOf:
          - type: string
          - type: 'null'
          title: Display Name
        default_role_names:
          anyOf:
          - items:
              type: string
            type: array
          - type: 'null'
          title: Default Role Names
        system_type:
          anyOf:
          - $ref: '#/components/schemas/SystemTypes'
          - type: 'null'
        name:
          type: string
          maxLength: 40
          minLength: 3
          pattern: ^[a-z0-9]+[a-z0-9-]+$
          title: Name
      type: object
      required:
      - name
      title: CreateOrganisationInput
    OrganisationName:
      properties:
        name:
          type: string
          maxLength: 40
          minLength: 3
          pattern: ^[a-z0-9]+[a-z0-9-]+$
          title: Name
      type: object
      required:
      - name
      title: OrganisationName
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    OAuth2AuthorizationCodeBearer:
      type: oauth2
      flows:
        authorizationCode:
          scopes: {}
          authorizationUrl: https://blocks.simbachain.com/api/member-service-validator/oauth/authorize
          tokenUrl: https://blocks.simbachain.com/api/member-service-validator/oauth/token
